spring:
  application:
    name: file_download

download:
  folder: Lesson17_Spring/file_download/downloads    # Путь для сохранения файлов
  threads: 3               # Количество потоков для загрузки
  speed-limit: 500         # Ограничение скорости загрузки (кБ/сек)

links-file: "classpath:links.txt"  # Файл со ссылками


server:
  port: 8080
